/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;
import com.mysql.cj.util.StringUtils;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author admin
 */
public class selling extends javax.swing.JFrame {

    /**
     * Creates new form selling
     */
    public selling() {
       
        try {
            initComponents();
            showProductList();
            showCustomer();
            SPName.setEditable(false);
            SPPrice.setEditable(false);  
            SPSeller.setEditable(false);
             icon();
        
        } catch (SQLException ex) {
            Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SPSeller = new javax.swing.JTextField();
        SPPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SPAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SPTable = new javax.swing.JTable();
        SPName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SPQty = new javax.swing.JTextField();
        SPBPrint = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        SPBTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SPGTotal = new javax.swing.JTextField();
        Search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        CBName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CTable = new javax.swing.JTable();
        CName = new javax.swing.JTextField();
        CPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CCustomer = new javax.swing.JButton();
        Csearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eres");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setText("Billing Portal");

        SPSeller.setText("User");
        SPSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPSellerActionPerformed(evt);
            }
        });

        SPPrice.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Seller Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Product");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Price");

        SPAdd.setBackground(new java.awt.Color(255, 51, 51));
        SPAdd.setText("ADD TO BILL");
        SPAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Bill Preview");

        SPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        SPTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SPTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(SPTable);

        SPName.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Qty");

        SPBPrint.setBackground(new java.awt.Color(0, 153, 0));
        SPBPrint.setText("Print");
        SPBPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPBPrintActionPerformed(evt);
            }
        });

        SPBTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { null,null,null,null,null}
            },
            new String [] {
                "ID", "Product Name", "Price", "Qty", "Total"
            }
        ));
        SPBTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SPBTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(SPBTable);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        SPGTotal.setBackground(new java.awt.Color(0, 0, 0));
        SPGTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SPGTotal.setForeground(new java.awt.Color(51, 255, 0));
        SPGTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPGTotalActionPerformed(evt);
            }
        });

        Search.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                SearchInputMethodTextChanged(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Search");

        jButton3.setBackground(new java.awt.Color(255, 204, 102));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CBName.setBackground(new java.awt.Color(102, 102, 102));
        CBName.setForeground(new java.awt.Color(51, 255, 0));

        jLabel11.setText("Customer Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(SPName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(SPQty, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(55, 55, 55)
                                        .addComponent(SPAdd))
                                    .addComponent(jLabel4)
                                    .addComponent(SPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(464, 464, 464))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SPBPrint)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(SPGTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SPSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SPGTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(SPBPrint)
                            .addComponent(jButton3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2)
                            .addComponent(SPSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SPQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(SPAdd)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        CTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "phone", "Total parchase"
            }
        ));
        CTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(CTable);

        jLabel9.setText("Customer Name");

        jLabel10.setText("Phone");

        CCustomer.setBackground(new java.awt.Color(51, 153, 0));
        CCustomer.setText("Create");
        CCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCustomerActionPerformed(evt);
            }
        });

        Csearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CsearchKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Search by Phone Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(CPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(CCustomer))
                            .addComponent(jLabel9)
                            .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Csearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Csearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4)
                                .addComponent(CPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CCustomer)
                                .addComponent(jButton1)))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
     private void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    int billId;
     ResultSet rs1 =null;
     Statement st1=null;
    private int coutProd(){
      
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022");
            st1 = con.createStatement();
            rs1 =st1.executeQuery("SELECT MAX(ID) FROM salesreport");
            rs1.next();
            billId =rs1.getInt(1)+1;
            
        }catch(SQLException e){
            
        }
        return billId;
    }
    private void insertBill(){
       
             try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022")) {
                   int id =coutProd();
               
                    PreparedStatement pst = con.prepareStatement("INSERT INTO salesreport VALUES(?,?,?,?,?)");
                    
                    Statement st = con.createStatement();
                    ResultSet totals = st.executeQuery("SELECT CTPurchase FROM customer  WHERE Cphone='"+CPhone.getText()+"'");
                    totals.next();
                    double pTotal =Double.parseDouble(totals.getString("CTPurchase"));
                    System.out.print(grandTotal+pTotal);
                    double pushToatl = grandTotal+pTotal;
                    PreparedStatement pst1 = con.prepareStatement("UPDATE customer SET CTPurchase=? WHERE Cphone='"+CPhone.getText()+"'");
                    pst1.setDouble(1, pushToatl);
                    int rows =pst1.executeUpdate();
                    pst.setInt(1, id);
                    pst.setString(2, SPSeller.getText());
                    pst.setDouble(3,grandTotal);

                    Date today =new Date(System.currentTimeMillis());
                    pst.setString(4, today.toString());
                    pst.setString(5, CBName.getText());
                    int row =pst.executeUpdate();
                    showCustomer();
                    con.close();
                    System.out.print(rows);
                   
                }
                JOptionPane.showMessageDialog(this,"Bill Added"); ;
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
    private void showProductList() throws SQLException, ClassNotFoundException{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM verse.products");
            SPTable.setModel(DbUtils.resultSetToTableModel(rs));          
 }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new userlogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SPSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPSellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPSellerActionPerformed
    int key = 0;
    private void SPTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SPTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) SPTable.getModel();
        int row = SPTable.getSelectedRow();
        key =Integer.parseInt(model.getValueAt(row, 0).toString());
        SPName.setText(model.getValueAt(row, 1).toString());
        SPPrice.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_SPTableMouseClicked
    double grandTotal;
    double total;
    private void SPAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPAddActionPerformed
        // TODO add your handling code here:
        
        
        if(SPName.getText().isEmpty() || SPQty.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Hello, Some Input Missing, i will wait fix and come back");
        }else{
            
         total = Double.valueOf(SPPrice.getText())*Integer.valueOf(SPQty.getText());
        DefaultTableModel model =(DefaultTableModel) SPBTable.getModel();
        String nextRowId=Integer.toString(model.getRowCount());
        grandTotal += total;
        SPGTotal.setText(grandTotal+" "+"Rs");
      model.addRow(new Object[]{
          nextRowId,
          SPName.getText(),
          SPPrice.getText(),
          SPQty.getText(),
          total
      });
      SPQty.setText("");
      Search.setText("");
            try {
                showProductList();
            } catch (SQLException ex) {
                Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SPAddActionPerformed

    private void SPBTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SPBTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SPBTableMouseClicked

    private void SPGTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPGTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPGTotalActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) SPBTable.getModel();
        model.setRowCount(1);
        grandTotal=0.0;
        SPGTotal.setText(grandTotal+" "+"Rs");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SPBPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPBPrintActionPerformed
        // TODO add your handling code here:
        if(!CBName.getText().isEmpty()){
        try{
            insertBill();
            SPBTable.print();
            
        }catch(PrinterException e){
            System.out.print(e);
        }
        }else{
         JOptionPane.showMessageDialog(this,"Sorry, No Customer No bill");
  
        }
    }//GEN-LAST:event_SPBPrintActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_SearchKeyPressed

    private void SearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_SearchInputMethodTextChanged
        // TODO add your handling code here:
  
    }//GEN-LAST:event_SearchInputMethodTextChanged

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        // TODO add your handling code here:
                 if(!Search.getText().isEmpty()){
        try{// TODO add your handling code here:
         Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM products WHERE ID='"+Search.getText()+"'");
            SPTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch (ClassNotFoundException | SQLException e){
            System.out.print(e);
        }
        }else{
            try {
                showProductList();
            } catch (SQLException ex) {
                Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SearchKeyReleased
    int prodId;
    private int cCount(){
         try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022");
            Statement st2 = con.createStatement();
            ResultSet rs2 =st2.executeQuery("SELECT MAX(ID) FROM customer");
            rs2.next();
            prodId =rs2.getInt(1)+1;
            
        }catch(SQLException e){
            
        }
        return prodId;
    }
       private void showCustomer() throws SQLException, ClassNotFoundException{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM verse.customer");
            CTable.setModel(DbUtils.resultSetToTableModel(rs));          
    }
    private void CCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCustomerActionPerformed
        // TODO add your handling code here:
        if(CName.getText().isEmpty() || CPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Customer is waiting fill all the field"); 
        }else{
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022")) {
                    
                      Statement st = con.createStatement();
                      ResultSet rs = st.executeQuery("SELECT * FROM customer WHERE CPhone like '" + CPhone.getText() + "%'");
                    if(!rs.next()){  
                    int id =cCount();
                    PreparedStatement pst = con.prepareStatement("INSERT INTO customer VALUES(?,?,?,?)");
                    pst.setInt(1, id);
                    pst.setString(2, CName.getText());
                    pst.setString(3, CPhone.getText() );
                    pst.setInt(4, 0);
                    int row =pst.executeUpdate();
                    System.out.print(row);
                    showCustomer();
                    JOptionPane.showMessageDialog(this,"Customer Added"); 
                    }else{
                      JOptionPane.showMessageDialog(this,"Customer Found select from field"); 
                       try{// TODO add your handling code here:
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection cone = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022");
                        Statement stc = cone.createStatement();
                        ResultSet rsc = stc.executeQuery("SELECT * FROM customer WHERE CPhone like '" + CPhone.getText() + "%'");
                        CTable.setModel(DbUtils.resultSetToTableModel(rsc));
          
        }catch (ClassNotFoundException | SQLException e){
            System.out.print(e);
        }
                    }
                }
                
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CCustomerActionPerformed

    private void CsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CsearchKeyReleased
        // TODO add your handling code here:
       if(!Csearch.getText().isEmpty()){
        try{// TODO add your handling code here:
         Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verse","root","Sql@2022");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM customer WHERE CPhone like '" + Csearch.getText() + "%'");
            CTable.setModel(DbUtils.resultSetToTableModel(rs));
          
        }catch (ClassNotFoundException | SQLException e){
            System.out.print(e);
        }
        }else{
            try {
                showCustomer();
            } catch (SQLException ex) {
                Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_CsearchKeyReleased

    private void CTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) CTable.getModel();
        int row = CTable.getSelectedRow();
        CName.setText(model.getValueAt(row, 1).toString());
        CBName.setText(model.getValueAt(row, 1).toString());
        CPhone.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_CTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            CName.setText("");
            CPhone.setText("");
            showCustomer();
            CBName.setText("");
            Csearch.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(selling.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CBName;
    private javax.swing.JButton CCustomer;
    private javax.swing.JTextField CName;
    private javax.swing.JTextField CPhone;
    private javax.swing.JTable CTable;
    private javax.swing.JTextField Csearch;
    private javax.swing.JButton SPAdd;
    private javax.swing.JButton SPBPrint;
    public javax.swing.JTable SPBTable;
    private javax.swing.JTextField SPGTotal;
    private javax.swing.JTextField SPName;
    private javax.swing.JTextField SPPrice;
    private javax.swing.JTextField SPQty;
    private javax.swing.JTextField SPSeller;
    private javax.swing.JTable SPTable;
    private javax.swing.JTextField Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
